include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - avoid_final_parameters
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations