include: package:lint/package.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_catching_errors: false
    constant_identifier_names: false

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true

  exclude:
    - lib/src/unicode.g.dart
